server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: lokitest-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: lokitest-api
          __path__: /var/log/lokitest-api/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            source: source
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          source:
      - output:
          source: message

  - job_name: container-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: container-logs
          __path__: /var/log/containers/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            stream: stream
            log: log
            kubernetes:
      - json:
          expressions:
            pod_name: pod_name
            container_name: container_name
            namespace: namespace
          source: kubernetes
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          pod_name:
          container_name:
          namespace:
      - output:
          source: log
